feat: Convert nrg-list to glimmer component
knoxville-utilities-board/ember-nrg-ui pull request #334
Opened 2021-11-12 18:45 UTC by KeithClinard

2021-11-12 20:15 UTC, TSenter requested changes

2021-11-12 20:15 UTC, TSenter commented on addon/components/nrg-list.hbs
> +        changePage=(action this.onChangePage)
Do these need the `action` helper?

2021-11-15 14:17 UTC, KeithClinard commented on addon/components/nrg-list.js
> +      this.args.onRefresh?.(query) ?? this.args.onQuery?.(query);
The intent is to call the `onRefresh` function if it is defined and `onQuery` if it is not.
I'll tweak the logic a bit.

2021-11-15 14:18 UTC, KeithClinard commented on addon/components/nrg-list.js
> +    return this.args.groupHeaderHandler?.(...arguments) ?? '';
That function should return the string of the group header.

2021-11-15 14:25 UTC, KeithClinard commented on tests/dummy/app/view-components/nrg-list/controller.js
> -    const query = this.query || {};
Since query is now defaulted to an empty object `query = {};` we shouldn't need to coerce it.

2021-11-15 17:01 UTC, TSenter commented on tests/dummy/app/view-components/nrg-list/controller.js
> +        include = item.animal === this.query?.animal;
```suggestion
      if (query.animal) {
        include = item.animal === query.animal;
```

2021-11-15 17:01 UTC, TSenter commented on tests/dummy/app/view-components/nrg-list/controller.js
> +            -1;
```suggestion
      if (query.search) {
        include =
          include &&
          item.name.toLowerCase().indexOf(query.search?.toLowerCase()) !==
            -1;
```

2021-11-15 21:43 UTC, TSenter approved these changes

2021-11-15 21:43 UTC, merged